#!/usr/bin/env python3
"""Generate crates/ext4-core/src/casefold_data.rs from Python's unicodedata:
the NFD-of-casefold mapping ("nfdicf", as the kernel's utf8 tables) for
every code point that changes (Hangul syllables are decomposed in code),
and the canonical combining classes. Usage: tools/gen-casefold.py"""
import os, sys, unicodedata

def is_hangul(cp):
    return 0xAC00 <= cp <= 0xD7A3

def nfdicf(s):
    # Full case folding of the NFD form, normalized again (as mkutf8data).
    return unicodedata.normalize("NFD", unicodedata.normalize("NFD", s).casefold())

maps, ccc = [], []
for cp in range(0x110000):
    if 0xD800 <= cp <= 0xDFFF or is_hangul(cp):
        continue
    c = chr(cp)
    if unicodedata.category(c) == "Cn":
        continue
    m = nfdicf(c)
    if m != c:
        maps.append((cp, m))
    k = unicodedata.combining(c)
    if k:
        ccc.append((cp, k))

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
out = os.path.join(root, "crates/ext4-core/src/casefold_data.rs")
data, index = [], []
for cp, m in maps:
    index.append((cp, len(data), len(m)))
    data.extend(ord(x) for x in m)
with open(out, "w") as f:
    f.write("// Generated by tools/gen-casefold.py from Unicode %s. Do not edit.\n\n"
            % unicodedata.unidata_version)
    f.write("/// (code point, offset into MAP_DATA, length), sorted.\n")
    f.write("pub static MAP_INDEX: [(u32, u16, u8); %d] = [\n" % len(index))
    for cp, off, n in index:
        f.write("    (0x%X, %d, %d),\n" % (cp, off, n))
    f.write("];\n\npub static MAP_DATA: [u32; %d] = [\n" % len(data))
    for i in range(0, len(data), 12):
        f.write("    " + ", ".join("0x%X" % x for x in data[i:i + 12]) + ",\n")
    f.write("];\n\n/// (code point, canonical combining class), sorted.\n")
    f.write("pub static CCC: [(u32, u8); %d] = [\n" % len(ccc))
    for cp, k in ccc:
        f.write("    (0x%X, %d),\n" % (cp, k))
    f.write("];\n")
print("%d mappings (%d code points), %d combining classes" % (len(index), len(data), len(ccc)))
