#!/usr/bin/env python3
"""Generate a LinuxKPI group list (src/linuxkpi/groups/NAME.list) from a
Linux kbuild Makefile, evaluated by GNU make with RustOS's configuration
(tools/kbuild-objs.mk). For drivers too large to list by hand (amdgpu).

  tools/kbuild-group.py --linux LINUX --src drivers/gpu/drm/amd/amdgpu \\
      --obj amdgpu-y --module amdgpu --out src/linuxkpi/groups/amdgpu.list

Files built with the FPU in Linux (CFLAGS_x.o += $(CC_FLAGS_FPU)) get
-msse -msse2 in a cflags section of their own; they only run
inside kernel_fpu_begin/end. Other per-file flags are left out (warnings
are off in LinuxKPI builds) except -I and -D.
"""
import argparse
import os
import shlex
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FPU = ["-msse", "-msse2"]


def keep_flags(flags, linux):
    out = []
    i = 0
    while i < len(flags):
        f = flags[i]
        if f in ("-I", "-D") and i + 1 < len(flags):
            f = f + flags[i + 1]
            i += 1
        if f.startswith("-I"):
            p = os.path.normpath(f[2:])
            if p.startswith(linux):
                p = "@LINUX@" + p[len(linux):]
            out.append("-I" + p)
        elif f.startswith("-D"):
            out.append(f)
        i += 1
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--linux", required=True)
    ap.add_argument("--src", required=True, help="Makefile/Kbuild directory, relative to the Linux tree")
    ap.add_argument("--obj", required=True, help="object variable, e.g. amdgpu-y")
    ap.add_argument("--module", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--comment", default="")
    ap.add_argument("--config", default=os.path.join(ROOT, "third_party/linux/generated/dot-config"),
                    help="the .config to evaluate with (default: RustOS's generated one)")
    a = ap.parse_args()
    linux = os.path.abspath(a.linux)
    src = os.path.join(linux, a.src)
    out = subprocess.run(
        ["make", "-s", "-f", os.path.join(ROOT, "tools/kbuild-objs.mk"), f"LINUX={linux}",
         f"CONFIG={os.path.abspath(a.config)}",
         f"SRC={src}", f"OBJ={a.obj}", "print"],
        capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(out.stderr)
    objs, common, per = [], [], {}
    for line in out.stdout.splitlines():
        key, _, val = line.partition(" ")
        if key == "OBJS":
            objs = val.split()
        elif key == "CCFLAGS":
            common = keep_flags(shlex.split(val), linux)
        elif key.startswith("CFLAGS_") and not key.startswith("CFLAGS_REMOVE_"):
            per[key[len("CFLAGS_"):]] = shlex.split(val)
    sections = {}  # extra flags (tuple) -> files
    missing = []
    seen = set()
    for o in objs:
        if o in seen or not o.endswith(".o"):
            continue
        seen.add(o)
        path = os.path.normpath(os.path.join(a.src, o[:-2] + ".c"))
        if not os.path.exists(os.path.join(linux, path)):
            missing.append(path)
            continue
        flags = per.get(o, [])
        extra = keep_flags(flags, linux)
        if any(f in ("-msse", "-msse2") for f in flags):
            extra = FPU + extra
        sections.setdefault(tuple(extra), []).append(path)
    with open(a.out, "w") as f:
        f.write(f"# {a.comment or a.module}\n")
        f.write(f"# Generated by tools/kbuild-group.py from {a.src}/Makefile ({a.obj});\n")
        f.write("# regenerate after a Linux update or a configuration change.\n")
        for extra, files in sorted(sections.items(), key=lambda kv: len(kv[0])):
            f.write(f"module: {a.module}\n")
            f.write("cflags: " + " ".join(common + list(extra)) + "\n")
            for p in files:
                f.write(p + "\n")
    print(f"{a.out}: {sum(len(v) for v in sections.values())} files, "
          f"{sum(len(v) for k, v in sections.items() if '-msse' in k)} with FPU, "
          f"{len(missing)} missing")
    for m in missing[:20]:
        print("  missing:", m)


if __name__ == "__main__":
    main()
