#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Import Linux sources for LinuxKPI into third_party/linux.

  tools/linux-import.py --linux ~/src/linux config
      Generate Kconfig output (autoconf.h, auto.conf) and the other
      generated headers Linux's own headers need (bounds.h, rq-offsets.h,
      asm-offsets.h, cpufeaturemasks.h, syscall tables, uapi wrappers) into
      third_party/linux/generated/.

  tools/linux-import.py --linux ~/src/linux import GROUP...
      Copy each group's .c files (src/linuxkpi/groups/GROUP.list) and every
      header they include (from clang's dependency output, with
      src/linuxkpi/include overrides taking precedence) into
      third_party/linux, and record them in MANIFEST.

  tools/linux-import.py check
      Verify MANIFEST against the files (licence tag, sha256).

  tools/linux-import.py undefined ARCHIVE...
      List symbols the given static libraries use but do not define.

The Linux checkout must be at the tag in third_party/linux/VERSION.
"""
import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
KPI = os.path.join(ROOT, "src", "linuxkpi")
DEST = os.path.join(ROOT, "third_party", "linux")
GROUPS = os.path.join(KPI, "groups")
FRAGMENT = os.path.join(KPI, "configs", "rustos.config")

# Licences that can be combined with RustOS (GPL-2.0-or-later) into a
# kernel distributed under GPLv2.
ALLOWED = {
    "GPL-2.0", "GPL-2.0-only", "GPL-2.0+", "GPL-2.0-or-later", "LGPL-2.1",
    "LGPL-2.1+", "LGPL-2.1-only", "LGPL-2.1-or-later", "MIT", "BSD-2-Clause",
    "BSD-3-Clause", "ISC", "Linux-OpenIB", "X11", "Zlib", "0BSD", "GPL-1.0+",
    "GPL-1.0-or-later",
}
# Linux's COPYING: files without an SPDX tag are GPL-2.0-only.
UNTAGGED = "GPL-2.0-only (untagged, per Linux COPYING)"
SPDX = re.compile(r"SPDX-License-Identifier:\s*(.+?)\s*(\*/|$)")


def run(cmd, **kw):
    print("+", " ".join(cmd), file=sys.stderr)
    return subprocess.run(cmd, check=True, **kw)


def cflags(linux, extra_gen=None):
    """The shared flag list with @LINUX@/@KPI@ substituted. When importing,
    @LINUX@ is the Linux checkout and generated headers come from DEST."""
    out = []
    with open(os.path.join(KPI, "cflags.txt")) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "@LINUX@/generated" in line:
                line = line.replace("@LINUX@/generated", extra_gen or os.path.join(linux, "generated"))
            out.append(line.replace("@LINUX@", linux).replace("@KPI@", KPI))
    return out


# ---------------------------------------------------------------- config

def kbuild_dir():
    d = os.path.join(ROOT, "target", "linux-kbuild")
    os.makedirs(d, exist_ok=True)
    return d


def make(linux, kb, *targets):
    run(["make", "-s", "-C", linux, "ARCH=x86_64", "LLVM=1", "O=" + kb] + list(targets))


def offsets_header(linux, kb, src, guard, extra_inc):
    """Compile `src` to assembly and turn its `->NAME $value comment`
    markers into #defines, as Linux's filechk_offsets does."""
    flags = [
        "--target=x86_64-linux-gnu", "-nostdinc", "-D__KERNEL__", "-std=gnu11",
        "-I" + os.path.join(linux, "arch/x86/include"),
        "-I" + os.path.join(kb, "arch/x86/include/generated"),
        "-I" + os.path.join(linux, "include"), "-I" + os.path.join(kb, "include"),
        "-I" + os.path.join(linux, "arch/x86/include/uapi"),
        "-I" + os.path.join(kb, "arch/x86/include/generated/uapi"),
        "-I" + os.path.join(linux, "include/uapi"),
        "-I" + os.path.join(kb, "include/generated/uapi"),
        "-include", os.path.join(linux, "include/linux/compiler-version.h"),
        "-include", os.path.join(linux, "include/linux/kconfig.h"),
        "-include", os.path.join(linux, "include/linux/compiler_types.h"),
        "-fno-PIE", "-mcmodel=kernel", "-mno-red-zone", "-mno-sse", "-mno-mmx",
        "-mno-sse2", "-mno-avx", "-w", "-DKBUILD_MODNAME=\"offsets\"",
        "-DKBUILD_BASENAME=\"offsets\"",
    ] + extra_inc
    r = subprocess.run(["clang"] + flags + ["-S", "-o", "-", os.path.join(linux, src)],
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("compiling %s failed:\n%s" % (src, r.stderr[-3000:]))
    asm = r.stdout
    lines = ["#ifndef " + guard, "#define " + guard,
             "/* Generated by tools/linux-import.py from " + src + ". */"]
    for raw in asm.splitlines():
        m = re.match(r'\s*\.ascii\s*"(.*)"', raw)
        if not m or not m.group(1).startswith("->"):
            continue
        body = m.group(1)[2:]
        if body.startswith("#"):
            lines.append("/* " + body[1:] + " */")
            continue
        if not body:
            lines.append("")
            continue
        parts = body.split(" ", 2)
        name, value = parts[0], parts[1].lstrip("$#")
        comment = parts[2] if len(parts) > 2 else ""
        lines.append("#define %s %s /* %s */" % (name, value, comment))
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def cmd_config(args):
    linux, kb = args.linux, kbuild_dir()
    make(linux, kb, "allnoconfig")
    run([os.path.join(linux, "scripts/kconfig/merge_config.sh"), "-m", "-O", kb,
         os.path.join(kb, ".config"), FRAGMENT], cwd=linux,
        env=dict(os.environ, ARCH="x86_64", LLVM="1"))
    make(linux, kb, "olddefconfig")
    # syncconfig writes autoconf.h; archheaders/asm-generic write the
    # syscall tables and asm-generic wrappers; cpufeaturemasks.h is its own
    # target.
    make(linux, kb, "syncconfig", "archheaders", "asm-generic",
         "arch/x86/include/generated/asm/cpufeaturemasks.h")
    gen = os.path.join(kb, "include", "generated")
    hz = re.search(r"^CONFIG_HZ=(\d+)$", open(os.path.join(kb, ".config")).read(), re.M).group(1)
    with open(os.path.join(gen, "timeconst.h"), "w") as f:
        f.write(subprocess.run(["bc", "-q", os.path.join(linux, "kernel/time/timeconst.bc")],
                               input=hz + "\n", capture_output=True, text=True, check=True).stdout)
    # The offsets headers depend on each other in this order.
    with open(os.path.join(gen, "bounds.h"), "w") as f:
        f.write(offsets_header(linux, kb, "kernel/bounds.c", "__LINUX_BOUNDS_H__", []))
    with open(os.path.join(gen, "rq-offsets.h"), "w") as f:
        f.write(offsets_header(linux, kb, "kernel/sched/rq-offsets.c", "__RQ_OFFSETS_H__",
                               ["-I" + os.path.join(linux, "kernel/sched")]))
    with open(os.path.join(gen, "asm-offsets.h"), "w") as f:
        f.write(offsets_header(linux, kb, "arch/x86/kernel/asm-offsets.c", "__ASM_OFFSETS_H__", []))

    out = os.path.join(DEST, "generated")
    if os.path.isdir(out):
        shutil.rmtree(out)
    for rel in ["include/generated", "arch/x86/include/generated"]:
        shutil.copytree(os.path.join(kb, rel), os.path.join(out, rel),
                        ignore=shutil.ignore_patterns("*.cmd", ".*"))
    shutil.copy(os.path.join(kb, ".config"), os.path.join(out, "dot-config"))
    print("generated headers written to", os.path.relpath(out, ROOT))


# ---------------------------------------------------------------- import

def group_files(name):
    path = os.path.join(GROUPS, name + ".list")
    files = []
    with open(path) as f:
        for line in f:
            line = line.split("#", 1)[0].strip()
            if line:
                files.append(line)
    return files


def licence_of(path):
    try:
        with open(path, errors="replace") as f:
            for _, line in zip(range(12), f):
                m = SPDX.search(line)
                if m:
                    return m.group(1).strip()
    except OSError:
        pass
    return None


def licence_ok(expr):
    if expr == UNTAGGED:
        return True
    # e.g. "GPL-2.0 OR MIT", "(GPL-2.0+ WITH Linux-syscall-note) OR BSD-3-Clause"
    expr = expr.replace("(", " ").replace(")", " ")
    for alt in re.split(r"\s+OR\s+", expr):
        ids = re.split(r"\s+AND\s+", alt)
        if all(i.split(" WITH ")[0].strip() in ALLOWED for i in ids):
            return True
    return False


def deps(linux, cfile):
    flags = cflags(linux, extra_gen=os.path.join(DEST, "generated"))
    mod = os.path.splitext(os.path.basename(cfile))[0]
    out = subprocess.run(
        ["clang"] + flags + ["-DKBUILD_MODNAME=\"%s\"" % mod, "-DKBUILD_BASENAME=\"%s\"" % mod,
                             "-M", os.path.join(linux, cfile)],
        capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("dependency scan failed for %s:\n%s" % (cfile, out.stderr[-4000:]))
    text = out.stdout.replace("\\\n", " ")
    files = text.split(":", 1)[1].split()
    linux_abs = os.path.realpath(linux)
    rel = []
    for p in files:
        p = os.path.realpath(p)
        if p.startswith(linux_abs + os.sep):
            rel.append(os.path.relpath(p, linux_abs))
    return rel


def read_manifest():
    m = {}
    path = os.path.join(DEST, "MANIFEST")
    if os.path.exists(path):
        with open(path) as f:
            for line in f:
                if line.startswith("#") or not line.strip():
                    continue
                rel, lic, sha = line.rstrip("\n").split("\t")
                m[rel] = (lic, sha)
    return m


def write_manifest(m):
    with open(os.path.join(DEST, "MANIFEST"), "w") as f:
        f.write("# path\tSPDX licence\tsha256 (generated by tools/linux-import.py)\n")
        for rel in sorted(m):
            f.write("%s\t%s\t%s\n" % (rel, m[rel][0], m[rel][1]))


def sha256(path):
    with open(path, "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()


def cmd_import(args):
    linux = args.linux
    if not os.path.isdir(os.path.join(DEST, "generated")):
        sys.exit("run `config` first")
    manifest = read_manifest()
    needed = set()
    for g in args.groups:
        for c in group_files(g):
            needed.add(c)
            needed.update(deps(linux, c))
    bad = []
    for rel in sorted(needed):
        src = os.path.join(linux, rel)
        lic = licence_of(src) or UNTAGGED
        if not licence_ok(lic):
            bad.append("%s (%s)" % (rel, lic))
            continue
        dst = os.path.join(DEST, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copyfile(src, dst)
        manifest[rel] = (lic, sha256(dst))
    write_manifest(manifest)
    print("%d files in MANIFEST (%d from this import)" % (len(manifest), len(needed) - len(bad)))
    if bad:
        print("refused (licence not compatible with GPL-2.0):", file=sys.stderr)
        for b in bad:
            print("  " + b, file=sys.stderr)
        sys.exit(1)


def cmd_check(args):
    manifest = read_manifest()
    errors = 0
    for rel, (lic, sha) in sorted(manifest.items()):
        path = os.path.join(DEST, rel)
        if not os.path.exists(path):
            print("missing:", rel)
            errors += 1
        elif sha256(path) != sha:
            print("modified (put changes in PATCHES/):", rel)
            errors += 1
        elif not licence_ok(lic):
            print("licence not allowed:", rel, lic)
            errors += 1
    print("%d files checked, %d problems" % (len(manifest), errors))
    sys.exit(1 if errors else 0)


def cmd_undefined(args):
    defined, used = set(), {}
    for a in args.archives:
        out = subprocess.run(["llvm-nm", "--format=just-symbols", "--defined-only", a],
                             capture_output=True, text=True, check=True).stdout
        defined.update(out.split())
        out = subprocess.run(["llvm-nm", "-A", "--undefined-only", a],
                             capture_output=True, text=True, check=True).stdout
        for line in out.splitlines():
            obj, sym = line.rsplit(" ", 1)
            used.setdefault(sym, set()).add(os.path.basename(obj.split(":")[-2] if obj.count(":") > 1 else obj))
    missing = sorted(s for s in used if s not in defined)
    for s in missing:
        print("%-40s %s" % (s, " ".join(sorted(used[s]))[:100]))
    print("%d undefined symbols" % len(missing), file=sys.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--linux", default=os.environ.get("LINUX_SRC"), help="Linux checkout")
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("config")
    p = sub.add_parser("import")
    p.add_argument("groups", nargs="+")
    sub.add_parser("check")
    p = sub.add_parser("undefined")
    p.add_argument("archives", nargs="+")
    args = ap.parse_args()
    if args.cmd in ("config", "import") and not args.linux:
        sys.exit("--linux DIR (or LINUX_SRC) is required")
    if args.linux:
        args.linux = os.path.realpath(args.linux)
    {"config": cmd_config, "import": cmd_import, "check": cmd_check,
     "undefined": cmd_undefined}[args.cmd](args)


if __name__ == "__main__":
    main()
