/* SPDX-License-Identifier: GPL-2.0-or-later */
/* Generated by Linux's build (include/generated/uapi/linux/version.h);
 * the pinned version, v6.18.54. */
#ifndef _RUSTOS_LINUX_VERSION_H
#define _RUSTOS_LINUX_VERSION_H
#define LINUX_VERSION_CODE 397878
#define KERNEL_VERSION(a, b, c) (((a) << 16) + ((b) << 8) + ((c) > 255 ? 255 : (c)))
#define LINUX_VERSION_MAJOR 6
#define LINUX_VERSION_PATCHLEVEL 18
#define LINUX_VERSION_SUBLEVEL 54
#endif
